### ISSUE TITLE
Fix zooming for logo

### ISSUE THREAD

**Issue by cferdinandi** [pawsnewengland/pawsne#43]
``` css
.logo {
    height: 1.5em;
    width: 9.61765em;
}

.logo .icon {
    height: 100%;
    width: 100%;
}
```
